name: .NET CI-CD Pipeline

on:
  push:
    branches: [ "main" ]

jobs:
  build-test-publish:

    runs-on: windows-latest

    steps:
    # 1. Checkout code
    - name: Checkout repository
      uses: actions/checkout@v4

    # 2. Setup .NET
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 10.0.x

    # 3. Restore dependencies
    - name: Restore dependencies
      run: dotnet restore WebAppBuild/WebAppBuild.slnx

    # 4. Build
    - name: Build solution
      run: dotnet build WebAppBuild/WebAppBuild.slnx --configuration Release --no-restore

    # 5. Publish
    - name: Publish app
      run: dotnet publish WebAppBuild/WebAppBuild.slnx -c Release -o publish --no-build

    # 6. Deploy directly
    - name: Deploy to IIS
      run: |
        Copy-Item -Path publish\* -Destination "D:\Deploy\WebAppBuild" -Recurse -Force
    
    # 7. Restart IIS App Pool
    - name: Restart IIS App Pool
      run: |
        Import-Module WebAdministration
        Restart-WebAppPool -Name "DefaultAppPool"
