name: .NET CI-CD Pipeline

on:
  push:
    branches: [ "main" ]
 
jobs:
  build-test-publish:
    runs-on: self-hosted

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 10.0.x

    - name: Restore dependencies
      run: dotnet restore WebAppBuild/WebAppBuild.slnx

    - name: Build solution
      run: dotnet build WebAppBuild/WebAppBuild.slnx --configuration Release --no-restore

    - name: Publish app
      run: dotnet publish WebAppBuild/WebAppBuild/WebAppBuild.csproj -c Release -o ${{ github.workspace }}\publish --no-build

    - name: Stop IIS App Pool
      shell: powershell
      run: |
        Import-Module WebAdministration -SkipEditionCheck
        Stop-WebAppPool -Name "DefaultAppPool"

    - name: Prepare deployment folder
      run: |
        if (!(Test-Path "D:\Deploy\WebAppBuild")) {
            New-Item -ItemType Directory -Path "D:\Deploy\WebAppBuild" -Force
        }

    - name: Deploy to IIS folder
      run: |
        Copy-Item -Path "${{ github.workspace }}\publish\*" `
                  -Destination "D:\Deploy\WebAppBuild" `
                  -Recurse -Force

    - name: Start IIS App Pool
      shell: powershell
      run: |
        Import-Module WebAdministration -SkipEditionCheck
        Start-WebAppPool -Name "DefaultAppPool"
