name: .NET CI-CD Pipeline

on:
  push:
    branches: [ "main" ]

jobs:
  build-test-publish:

    runs-on: windows-latest

    steps:
    # 1. Checkout code
    - name: Checkout repository
      uses: actions/checkout@v4

    # 2. Setup .NET
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 10.0.x

    # 3. Restore dependencies
    - name: Restore dependencies
      run: dotnet restore WebAppBuild.slnx

    # 4. Build
    - name: Build solution
      run: dotnet build WebAppBuild.slnx --configuration Release --no-restore

    # 5. Publish
    - name: Publish app
      run: dotnet publish WebAppBuild.slnx -c Release -o publish --no-build

    # 6. Upload artifact
    - name: Upload build artifact
      uses: actions/upload-artifact@v4
      with:
        name: dotnet-app
        path: publish
